name = "IPG"
uuid = "2f50017d-522a-4a0a-b317-915d5df6b243"
authors = ["Bruno Machado Pacheco <mpacheco.bruno@gmail.com>"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NormalGames = "4dc104ef-1e0c-4a09-93ea-14ddc8e86204"

[sources]
NormalGames = {rev = "optimizer-agnosticism", url = "https://github.com/mxmmargarida/Normal-form-games"}

[compat]
IterTools = "1.10.0"
JSON3 = "1.14.1"
JuMP = "1.23.6"
LinearAlgebra = "1.11.0"
Test = "1.11.0"

[extras]
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "SCIP", "LinearAlgebra"]
